//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AuthTokensTokenType.
const (
	Bearer AuthTokensTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthTokensTokenType enum.
func (e AuthTokensTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for GameStatus.
const (
	Active     GameStatus = "active"
	Archived   GameStatus = "archived"
	Complete   GameStatus = "complete"
	Draft      GameStatus = "draft"
	Paused     GameStatus = "paused"
	Recruiting GameStatus = "recruiting"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	case Complete:
		return true
	case Draft:
		return true
	case Paused:
		return true
	case Recruiting:
		return true
	default:
		return false
	}
}

// Defines values for OrderMessageSeverity.
const (
	Error   OrderMessageSeverity = "error"
	Info    OrderMessageSeverity = "info"
	Warning OrderMessageSeverity = "warning"
)

// Valid indicates whether the value is a known member of the OrderMessageSeverity enum.
func (e OrderMessageSeverity) Valid() bool {
	switch e {
	case Error:
		return true
	case Info:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for OrderSubmissionStatus.
const (
	Accepted   OrderSubmissionStatus = "accepted"
	Rejected   OrderSubmissionStatus = "rejected"
	Submitted  OrderSubmissionStatus = "submitted"
	Superseded OrderSubmissionStatus = "superseded"
)

// Valid indicates whether the value is a known member of the OrderSubmissionStatus enum.
func (e OrderSubmissionStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Rejected:
		return true
	case Submitted:
		return true
	case Superseded:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin  Role = "admin"
	Gm     Role = "gm"
	Player Role = "player"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Gm:
		return true
	case Player:
		return true
	default:
		return false
	}
}

// Defines values for TurnStatus.
const (
	Locked     TurnStatus = "locked"
	Open       TurnStatus = "open"
	Processing TurnStatus = "processing"
	Published  TurnStatus = "published"
)

// Valid indicates whether the value is a known member of the TurnStatus enum.
func (e TurnStatus) Valid() bool {
	switch e {
	case Locked:
		return true
	case Open:
		return true
	case Processing:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Email    openapi_types.Email `json:"email"`
	Id       int64               `json:"id"`
	IsActive bool                `json:"isActive"`
	IsAdmin  bool                `json:"isAdmin"`
	Roles    []Role              `json:"roles"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Account Account `json:"account"`
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken      string              `json:"accessToken"`
	ExpiresInSeconds int                 `json:"expiresInSeconds"`
	RefreshToken     string              `json:"refreshToken"`
	TokenType        AuthTokensTokenType `json:"tokenType"`
}

// AuthTokensTokenType defines model for AuthTokens.TokenType.
type AuthTokensTokenType string

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Email    openapi_types.Email `json:"email"`
	IsActive *bool               `json:"isActive,omitempty"`
	IsAdmin  *bool               `json:"isAdmin,omitempty"`

	// Secret Optional. If omitted, a random passphrase is generated. Minimum 8 characters.
	Secret *string `json:"secret,omitempty"`
}

// CreateAccountResponse defines model for CreateAccountResponse.
type CreateAccountResponse struct {
	Account Account `json:"account"`

	// GeneratedSecret The plaintext secret, present only when one was generated (secret
	// omitted from the request). Shown once; only its hash is stored.
	GeneratedSecret *string `json:"generatedSecret,omitempty"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// DatabaseVersion defines model for DatabaseVersion.
type DatabaseVersion struct {
	// SchemaVersion Number of schema migrations applied to the open database (SQLite user_version).
	SchemaVersion int32 `json:"schemaVersion"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	RequestId *string `json:"requestId,omitempty"`
}

// Game defines model for Game.
type Game struct {
	Description *string    `json:"description,omitempty"`
	Id          int64      `json:"id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Status      GameStatus `json:"status"`
}

// GameStatus defines model for GameStatus.
type GameStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ListAccountsResponse defines model for ListAccountsResponse.
type ListAccountsResponse struct {
	Accounts []Account `json:"accounts"`
}

// ListGamesResponse defines model for ListGamesResponse.
type ListGamesResponse struct {
	Games []Game `json:"games"`
}

// ListTurnsResponse defines model for ListTurnsResponse.
type ListTurnsResponse struct {
	Turns []Turn `json:"turns"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	User User `json:"user"`
}

// OrderMessage defines model for OrderMessage.
type OrderMessage struct {
	Line     *int                 `json:"line,omitempty"`
	Message  string               `json:"message"`
	Severity OrderMessageSeverity `json:"severity"`
}

// OrderMessageSeverity defines model for OrderMessage.Severity.
type OrderMessageSeverity string

// OrderSubmission defines model for OrderSubmission.
type OrderSubmission struct {
	FactionId   int64                  `json:"factionId"`
	GameId      int64                  `json:"gameId"`
	Id          int64                  `json:"id"`
	Status      OrderSubmissionStatus  `json:"status"`
	SubmittedAt time.Time              `json:"submittedAt"`
	TurnId      int64                  `json:"turnId"`
	Validation  *OrderValidationResult `json:"validation,omitempty"`
}

// OrderSubmissionStatus defines model for OrderSubmission.Status.
type OrderSubmissionStatus string

// OrderValidationResult defines model for OrderValidationResult.
type OrderValidationResult struct {
	Messages []OrderMessage `json:"messages"`
	Ok       bool           `json:"ok"`
}

// OrdersRequest defines model for OrdersRequest.
type OrdersRequest struct {
	FactionId int64  `json:"factionId"`
	Orders    string `json:"orders"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Role defines model for Role.
type Role string

// Turn defines model for Turn.
type Turn struct {
	GameId      int64      `json:"gameId"`
	Id          int64      `json:"id"`
	Label       string     `json:"label"`
	OrdersDueAt *time.Time `json:"ordersDueAt,omitempty"`
	Status      TurnStatus `json:"status"`
}

// TurnStatus defines model for TurnStatus.
type TurnStatus string

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	IsActive *bool `json:"isActive,omitempty"`
	IsAdmin  *bool `json:"isAdmin,omitempty"`

	// Secret New secret, minimum 8 characters.
	Secret *string `json:"secret,omitempty"`
}

// User defines model for User.
type User struct {
	DisplayName *string `json:"displayName,omitempty"`
	Id          int64   `json:"id"`
	Roles       []Role  `json:"roles"`
	Username    string  `json:"username"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Application Server application version (semver, including build metadata when available).
	Application string          `json:"application"`
	Database    DatabaseVersion `json:"database"`
}

// AccountId defines model for AccountId.
type AccountId = int64

// GameId defines model for GameId.
type GameId = int64

// SubmissionId defines model for SubmissionId.
type SubmissionId = int64

// TurnId defines model for TurnId.
type TurnId = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	Status *GameStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = CreateGameRequest

// SubmitOrdersJSONRequestBody defines body for SubmitOrders for application/json ContentType.
type SubmitOrdersJSONRequestBody = OrdersRequest

// ValidateOrdersJSONRequestBody defines body for ValidateOrders for application/json ContentType.
type ValidateOrdersJSONRequestBody = OrdersRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List accounts
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// Create an account
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// Get an account by id
	// (GET /accounts/{accountId})
	GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Exchange credentials for JWT tokens
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the presented refresh token or session family
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Exchange a refresh token for a new access token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// List games visible to the current user
	// (GET /games)
	ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams)
	// Create a game
	// (POST /games)
	CreateGame(w http.ResponseWriter, r *http.Request)
	// Get a game by id
	// (GET /games/{gameId})
	GetGame(w http.ResponseWriter, r *http.Request, gameId GameId)
	// List turns for a game
	// (GET /games/{gameId}/turns)
	ListTurns(w http.ResponseWriter, r *http.Request, gameId GameId)
	// Get a turn by id
	// (GET /games/{gameId}/turns/{turnId})
	GetTurn(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId)
	// Get an order submission
	// (GET /games/{gameId}/turns/{turnId}/orders/{submissionId})
	GetOrderSubmission(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId, submissionId SubmissionId)
	// Submit an order set for processing
	// (POST /games/{gameId}/turns/{turnId}/orders:submit)
	SubmitOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId)
	// Validate an order set without submitting it
	// (POST /games/{gameId}/turns/{turnId}/orders:validate)
	ValidateOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId)
	// Health check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get the authenticated user context
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Application and database schema version
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGame(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGame(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTurns operation middleware
func (siw *ServerInterfaceWrapper) ListTurns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTurns(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTurn operation middleware
func (siw *ServerInterfaceWrapper) GetTurn(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTurn(w, r, gameId, turnId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrderSubmission operation middleware
func (siw *ServerInterfaceWrapper) GetOrderSubmission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	// ------------- Path parameter "submissionId" -------------
	var submissionId SubmissionId

	err = runtime.BindStyledParameterWithOptions("simple", "submissionId", r.PathValue("submissionId"), &submissionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "submissionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrderSubmission(w, r, gameId, turnId, submissionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitOrders operation middleware
func (siw *ServerInterfaceWrapper) SubmitOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitOrders(w, r, gameId, turnId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateOrders operation middleware
func (siw *ServerInterfaceWrapper) ValidateOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateOrders(w, r, gameId, turnId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts", wrapper.ListAccounts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreateAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{accountId}", wrapper.GetAccount)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/accounts/{accountId}", wrapper.UpdateAccount)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games", wrapper.ListGames)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/games", wrapper.CreateGame)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}", wrapper.GetGame)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}/turns", wrapper.ListTurns)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}", wrapper.GetTurn)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}/orders/{submissionId}", wrapper.GetOrderSubmission)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}/orders:submit", wrapper.SubmitOrders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}/orders:validate", wrapper.ValidateOrders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ListAccountsRequestObject struct {
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse ListAccountsResponse

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAccounts401JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAccounts403JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse CreateAccountResponse

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateAccount403JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse AccountResponse

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAccount401JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAccount403JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAccount404JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
	Body      *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse AccountResponse

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAccount400JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAccount401JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateAccount403JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAccount404JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthTokens

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse AuthTokens

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListGamesRequestObject struct {
	Params ListGamesParams
}

type ListGamesResponseObject interface {
	VisitListGamesResponse(w http.ResponseWriter) error
}

type ListGames200JSONResponse ListGamesResponse

func (response ListGames200JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGames401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListGames401JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGameRequestObject struct {
	Body *CreateGameJSONRequestBody
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse Game

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGame400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGame401JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGame403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateGame403JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGameRequestObject struct {
	GameId GameId `json:"gameId"`
}

type GetGameResponseObject interface {
	VisitGetGameResponse(w http.ResponseWriter) error
}

type GetGame200JSONResponse Game

func (response GetGame200JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGame401JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGame403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetGame403JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGame404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGame404JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurnsRequestObject struct {
	GameId GameId `json:"gameId"`
}

type ListTurnsResponseObject interface {
	VisitListTurnsResponse(w http.ResponseWriter) error
}

type ListTurns200JSONResponse ListTurnsResponse

func (response ListTurns200JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurns401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTurns401JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurns403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListTurns403JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurns404JSONResponse struct{ NotFoundJSONResponse }

func (response ListTurns404JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurnRequestObject struct {
	GameId GameId `json:"gameId"`
	TurnId TurnId `json:"turnId"`
}

type GetTurnResponseObject interface {
	VisitGetTurnResponse(w http.ResponseWriter) error
}

type GetTurn200JSONResponse Turn

func (response GetTurn200JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurn401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTurn401JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurn403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetTurn403JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurn404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTurn404JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmissionRequestObject struct {
	GameId       GameId       `json:"gameId"`
	TurnId       TurnId       `json:"turnId"`
	SubmissionId SubmissionId `json:"submissionId"`
}

type GetOrderSubmissionResponseObject interface {
	VisitGetOrderSubmissionResponse(w http.ResponseWriter) error
}

type GetOrderSubmission200JSONResponse OrderSubmission

func (response GetOrderSubmission200JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmission401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOrderSubmission401JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmission403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetOrderSubmission403JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmission404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrderSubmission404JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrdersRequestObject struct {
	GameId GameId `json:"gameId"`
	TurnId TurnId `json:"turnId"`
	Body   *SubmitOrdersJSONRequestBody
}

type SubmitOrdersResponseObject interface {
	VisitSubmitOrdersResponse(w http.ResponseWriter) error
}

type SubmitOrders201JSONResponse OrderSubmission

func (response SubmitOrders201JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response SubmitOrders400JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SubmitOrders401JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders403JSONResponse struct{ ForbiddenJSONResponse }

func (response SubmitOrders403JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders404JSONResponse struct{ NotFoundJSONResponse }

func (response SubmitOrders404JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders409JSONResponse struct{ ConflictJSONResponse }

func (response SubmitOrders409JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrdersRequestObject struct {
	GameId GameId `json:"gameId"`
	TurnId TurnId `json:"turnId"`
	Body   *ValidateOrdersJSONRequestBody
}

type ValidateOrdersResponseObject interface {
	VisitValidateOrdersResponse(w http.ResponseWriter) error
}

type ValidateOrders200JSONResponse OrderValidationResult

func (response ValidateOrders200JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response ValidateOrders400JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ValidateOrders401JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders403JSONResponse struct{ ForbiddenJSONResponse }

func (response ValidateOrders403JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders404JSONResponse struct{ NotFoundJSONResponse }

func (response ValidateOrders404JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List accounts
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// Create an account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Get an account by id
	// (GET /accounts/{accountId})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)
	// Exchange credentials for JWT tokens
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the presented refresh token or session family
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Exchange a refresh token for a new access token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// List games visible to the current user
	// (GET /games)
	ListGames(ctx context.Context, request ListGamesRequestObject) (ListGamesResponseObject, error)
	// Create a game
	// (POST /games)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Get a game by id
	// (GET /games/{gameId})
	GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error)
	// List turns for a game
	// (GET /games/{gameId}/turns)
	ListTurns(ctx context.Context, request ListTurnsRequestObject) (ListTurnsResponseObject, error)
	// Get a turn by id
	// (GET /games/{gameId}/turns/{turnId})
	GetTurn(ctx context.Context, request GetTurnRequestObject) (GetTurnResponseObject, error)
	// Get an order submission
	// (GET /games/{gameId}/turns/{turnId}/orders/{submissionId})
	GetOrderSubmission(ctx context.Context, request GetOrderSubmissionRequestObject) (GetOrderSubmissionResponseObject, error)
	// Submit an order set for processing
	// (POST /games/{gameId}/turns/{turnId}/orders:submit)
	SubmitOrders(ctx context.Context, request SubmitOrdersRequestObject) (SubmitOrdersResponseObject, error)
	// Validate an order set without submitting it
	// (POST /games/{gameId}/turns/{turnId}/orders:validate)
	ValidateOrders(ctx context.Context, request ValidateOrdersRequestObject) (ValidateOrdersResponseObject, error)
	// Health check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get the authenticated user context
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Application and database schema version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request) {
	var request ListAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request GetAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request UpdateAccountRequestObject

	request.AccountId = accountId

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGames operation middleware
func (sh *strictHandler) ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams) {
	var request ListGamesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGames(ctx, request.(ListGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGamesResponseObject); ok {
		if err := validResponse.VisitListGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(w http.ResponseWriter, r *http.Request) {
	var request CreateGameRequestObject

	var body CreateGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGame operation middleware
func (sh *strictHandler) GetGame(w http.ResponseWriter, r *http.Request, gameId GameId) {
	var request GetGameRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGame(ctx, request.(GetGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameResponseObject); ok {
		if err := validResponse.VisitGetGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTurns operation middleware
func (sh *strictHandler) ListTurns(w http.ResponseWriter, r *http.Request, gameId GameId) {
	var request ListTurnsRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTurns(ctx, request.(ListTurnsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTurns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTurnsResponseObject); ok {
		if err := validResponse.VisitListTurnsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTurn operation middleware
func (sh *strictHandler) GetTurn(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId) {
	var request GetTurnRequestObject

	request.GameId = gameId
	request.TurnId = turnId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTurn(ctx, request.(GetTurnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTurn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTurnResponseObject); ok {
		if err := validResponse.VisitGetTurnResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrderSubmission operation middleware
func (sh *strictHandler) GetOrderSubmission(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId, submissionId SubmissionId) {
	var request GetOrderSubmissionRequestObject

	request.GameId = gameId
	request.TurnId = turnId
	request.SubmissionId = submissionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrderSubmission(ctx, request.(GetOrderSubmissionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrderSubmission")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderSubmissionResponseObject); ok {
		if err := validResponse.VisitGetOrderSubmissionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitOrders operation middleware
func (sh *strictHandler) SubmitOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId) {
	var request SubmitOrdersRequestObject

	request.GameId = gameId
	request.TurnId = turnId

	var body SubmitOrdersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitOrders(ctx, request.(SubmitOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitOrdersResponseObject); ok {
		if err := validResponse.VisitSubmitOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ValidateOrders operation middleware
func (sh *strictHandler) ValidateOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId) {
	var request ValidateOrdersRequestObject

	request.GameId = gameId
	request.TurnId = turnId

	var body ValidateOrdersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ValidateOrders(ctx, request.(ValidateOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ValidateOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ValidateOrdersResponseObject); ok {
		if err := validResponse.VisitValidateOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Bxrc9s28q/s8Dpz6Q0tKY+5NuonN0196dRJz3LSD7HvBiJXIhoSYAFQjurRf7/BgyQogpKcWG5zn2Ib",
	"wGLfLyxzGyW8KDlDpmQ0vY1KIkiBCoX57TRJeMXUq1T/Qlk0jUqisiiOGCkwmkakWY8jgb9XVGAaTZWo",
	"MI5kkmFB9MEFFwVR0TSiTP3zWRRHBWW0qIpo+jiO1LpEu4RLFNFmE0dnpMDBK5d28T7vm1XzgkpJORu8",
	"Vfpb7vPuy0oM36rs4v3dt9GgZMmZRCPf70l6gb9XKJX+LeFMITM/krLMaUIU5Wz8m+RM/6299CuBi2ga",
	"/W3c6s7YrsrxSyG4uHCX2CtTlImgpQYWTaNXbEVymoJwF2/i6AVni5wmD4iEoxoSd7OEG6oySCohkCnQ",
	"SgZSEYUavR+5mNM0RfZw+J1WKkOmNHRMoZIogEpgXAHJc36DKSgOJElQSlAZlSBQ8kokBt/XXP3IK5Y+",
	"JDvt7XBDLJYLc/8mjt4yUqmMC/oHPiA+59pW2TIG/Fhqu4mBC6BO8RKBqeYtyaUxQQfV83fGEQpeolDU",
	"GgoWhOYde7N/aWxMKkHZUlNM06BdbttiHFF5mii6Qr3drc45z5Ewt5oWlIUXBc8tXlRhIfex64LnRi8c",
	"HCIEWUfWF9Ru5b1GO26IalBr8agvvW7g8PlvmBj7dWxrJNJjH2n5ugvRmv3buNXHg3dXKrvkH5DJ4LUo",
	"pVn1+NiKymqHfMVmmHCWWkl/JEWZYzR9Ppns9qYax4VAmQ1foPTKpfnrbYRMA3offY9EoPCIqff3qW6w",
	"37rLhxwgI8SnFwKJwkZSjdM/VM8Lyn5GtlSZzwtP6z1lTnFBqlxF0wXJJca7lXv/ZomJQGX3+kb+xvxA",
	"8hG8WgAvqFLa0AkIwlJeQEmkLDNBJGrXuUSGQjvTEZxbmcK3kGREkEQnO6MobknWJ2+4SKN9ErK8OYDb",
	"92UXcdTQMRvgymWGUOZEa+lHBZZ3MZQCpQ5snOVruMmQAWfWWzcA4ZHdfMUcL2EheAEqwzpUfz2CWcZv",
	"9NkEv7OwqJKQEZlpHkvFBaajKxYdoNqDBm1Zp3PAQS3tUBwwO5s+3e7TWZlXS5vzKoVCM+8/78nJH5OT",
	"59fu35Prf3y1lxgDxl0aIugHosicSHyHQjqMu+RYMXvLXYm+roo5CuALsBuhoEthwqYEE0NtNqAFxUtk",
	"kLr74NHs3z9ThSZ9+O/Kgv96ZByG83HP4k6gevrETyAnwYS1Q3kH8RDt3UjdozzhKXacblT5+UJAZgVK",
	"SZZbh+pESPtErYiFDf9e0A+Bclpts+/dIjZ4tpeHKD1zOnc3TT04WahV+t6UOI50flvtTR40XTO7M5gy",
	"+NrfwBxi0Ky5sg6GqSALZcJbIiqqNGpxROrkoySVNHqgEctR6b8RkWR0hWkggMbRv5DkKhtWuJbmVnv4",
	"hxB3Vq05tlsno8ejyX6HYC9pYYTY8TOVyvl1uTdAHJ7reaFiZ7rXAB7CTYtrB2K6QjocK2Mc+1CyIIfw",
	"0YXyDnx0qXw4PhrYXnwsyCA+fEnZYHRq0gffsr2cYk9U0t76oAC2hW5zLm4vG0CeV8MZ4HZOuw+FHvxz",
	"HJaSxnGfbN7KQKQxB0PUvBEpivM2KHTvyymr+bgjjfdiSt9J4goFVWvfZ1G24FEc3RDBrL9CHeX2J/QN",
	"rN2RxJDU9qT6VC20f6ybVQfEjmXTTzukKj10o+z5ctMk05mjceEJlvZHgZoy86OsShQS0wHv3QA4VR0k",
	"UqLwRFGj2/0aq+mgHYC0SQZIHY53qaGRwrtm+wVKXaUEQ2DTkmz6da2E4jYa+NQNyr13Y0/6TnUOd3Yd",
	"E+k5vVjHv0CTYYtQEySbqwfRl4N+ZbfS7jZQbkDf1SH6QnAQQnhfeA7v3ryij0fnbBADnncaBGVO1ii0",
	"YhXakkylHDIXE8WCkfn+rT0nc8y7ydCs1IjA88njkFlajv9Q4Q5bZlWek7kGZtvan5iiaj7sSlEb+7RE",
	"7MxSPVieRHRdpc/z5IPxY6XguuKw3r+s5jmV2YBPe1umB/RdPqMXONQeeY03TflffFbLo8ekty6Mb9U6",
	"VGrNfT1UqRysa/fR3ezmUbsN1CiJlz4NNzpdqbsjX2972n2JzFCsUIC3B1yFAI8kFisUMVCW5FWq7Wpe",
	"0TyFAhXRBb1t2pAVocZiumW8rUtOSF5mJGSLdUdgHyu3OxW9osGjzoPa55RVy0onOzMN2zJnbhqfp5X2",
	"mvVvP9bq8NOvl5HrxRsFt03SBnKmVGk7/Sb76vH2BWdKK/bJggqp4OLl7BJOf3kFCy6AMMCPJQpaIFMk",
	"hzNuH3hucA7SyGR0xa7YZUalOUMlUPNKYdqL+RpkQfIcCEshySrBThaCIkvz9QguBRJlX2AWNEcgElSG",
	"V8z4hAQSh5VBw7r1kxuhkwAGSU4180fg1OKHyzfS3JERluYoQKpqLoEIvGJtk8715Or7zKsVJyU9SXiK",
	"S2Su+0aV0YuXHbI1ze6y019eefWpVqAno4lx2yUyUtJoGj0dTUZPTTGhMiO+sV+MLkMux3gp0xccwQWa",
	"+gkM59zBGExUwBTma6Cp1mFtPKRODDpFcbT1VvlkMrm3B6Rg8R16hqtx2cTRs8njIbANnuPOc5c59HT/",
	"ofZ90RhOVRRErB03Gt5pqZKl1GbYYHW9iaOSyz2SsA1VrVs1sBhuMppkVtFts8VoHuPsxKQbULEcpbxi",
	"dVyCMbggpBUSJCrTdbfxRcOpe8bh9ruvwfoiYZQDU9NJBspgq6092FyOr5jkQM2VsulFW9MkjHEFcwSB",
	"CV9h04ruqlinMx81XcDvebq+N/UKvrVsut5UZzybnoo/PhYOe3UcEnPAae1kv9Z6swMPZR36xPP9J5px",
	"gq45WY54ZhA2qU3cerrxbTPhsjnI680wN7XukIM7Q+Wr3pHc2x2knqIiNJcPKsJn+080IwxdEZ6h8uRn",
	"mTzoGL1Jpvfh+9ot43bSaXNtYl6S3UnS8HKFYg0Linlq/KF7nPwOSPP4Vi9eMWnoSA0t884a5LhQULEk",
	"I2yJ6QhOFeRIpDIPdi2E2pGM4BRYk+lDUUnjAkl9qpPxB9xhpzw5kjsMlkAHucM/xSQqg+5f3hF+uhVZ",
	"eRzmCCuVjXO+tMVnnWtsJW1m+a6q44oX90pWmJR+RfIKuy10s3biladtWeeWbLNk007y7E3+/O79Q6th",
	"O60S0ECDGcgqSdD0SD9NnbziK5q+v/Yl//Kj9Sv+DJSpTX769dI+n3byTF2pdfWAV2qnIuj14ziR7rPF",
	"pj/L+MRaRI+jvDJJtO1GfzpHGx5e4Ip/QPPc7hw76oTW9PjcEzQXINE072FBCpqvdzDVnRzm6kV38OcY",
	"vA21QP9ShmFWGiY/hIGQLZGaPoKJtP6wQViuzduoSxf7Na55XI16OYoZAf69QrH2Jo+b54OD+Nh5rr8+",
	"cgndfSMOyO0dlXSeI1iO3IPxmZLYQIOVg+1GX+rRXfNS2IrFcnq4UL6wGm6rY5veCTg7B8FzHA0Uj2eu",
	"TXi0ytEffnrgstG+1PclaZpHX0CJGKz4jMYElKIx1vGtfSPYDFrtGapG7EeyqJ2s/wLrNNtk3a7RPIO8",
	"U4HmPgrZXPeFNm6GPwYdrpkeOXZHsTuiEgpjpiOqQ4n2WEs3FPMFyNO4XdVg3zMoy94jCHV8a9/Udxqm",
	"eQc9omzttFBYnF+kYWqe9gzzc2UY793pvnU6QNpj+3o8vvW/u9qpA9tDM0dUh+2rAprRrn6ZDTbDfpA+",
	"O2s1eeMmKR5AT/bv7Hy5d7heTe0ozvb3jkfR9XigrDOoK8fN4yST3YmcB04k72YlX8jjw50M6/NeK6x+",
	"eMaI7hXZHz3pGeXBFuAG4fBPtQE37IafaAV+C3FOJE06PURv4OybdoQsevv61SU8njyG8zfvXsLrK+b+",
	"8ARmL968vYSXV+wuzcRPsLF7jkSBGcV+Hd7sAeE2/b82t2ud6lrODVUZrxS4GUzKlkDVkAFl5iOCP3al",
	"G/Y7g2NmGVtfMoTcJ4oVTczXbaJirJ5sGmptWYCQZJh88CifraXCwlFup6WGiD4/avnrzY0HiH3ht3fu",
	"oZGkEx1dhJH+h9aGmo++dpyj44/3UUjwKbgeejEfzVmZuAmjv8vg3BdhqdlsmXDF6r/zRf97rhH8YqaK",
	"vgPGfbytVbvnwMAT3xmqeqDriOLbHo0LeSFHHGV2CLAeMRvS2FOPYZpRzYdt7ju4VUNVX5m7YLuzZ++v",
	"dUiycrEhb/vRICE5pLjCnJeF1jq7N4qjSuRuGG06Hud6X8almj5//u03Js45RLYhOtvTREhntfVgX9vp",
	"dcjrwDr4nwE0OmOa0jldYLJOcmyBGAp3guiruTt6joGDtu9HFMn50uGvqrI9dOY6u7eh2rgZXjQHzX+n",
	"0By05Wb/oPHE0M7px14ZEjeATEfcQXK+O0C0e9A1fV0qlbUJeESaZ/yvPcY1o17Xm/8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
