//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AuthTokensTokenType.
const (
	Bearer AuthTokensTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthTokensTokenType enum.
func (e AuthTokensTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for GameStatus.
const (
	Active     GameStatus = "active"
	Archived   GameStatus = "archived"
	Complete   GameStatus = "complete"
	Draft      GameStatus = "draft"
	Paused     GameStatus = "paused"
	Recruiting GameStatus = "recruiting"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	case Complete:
		return true
	case Draft:
		return true
	case Paused:
		return true
	case Recruiting:
		return true
	default:
		return false
	}
}

// Defines values for OrderMessageSeverity.
const (
	Error   OrderMessageSeverity = "error"
	Info    OrderMessageSeverity = "info"
	Warning OrderMessageSeverity = "warning"
)

// Valid indicates whether the value is a known member of the OrderMessageSeverity enum.
func (e OrderMessageSeverity) Valid() bool {
	switch e {
	case Error:
		return true
	case Info:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for OrderSubmissionStatus.
const (
	Accepted   OrderSubmissionStatus = "accepted"
	Rejected   OrderSubmissionStatus = "rejected"
	Submitted  OrderSubmissionStatus = "submitted"
	Superseded OrderSubmissionStatus = "superseded"
)

// Valid indicates whether the value is a known member of the OrderSubmissionStatus enum.
func (e OrderSubmissionStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Rejected:
		return true
	case Submitted:
		return true
	case Superseded:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin  Role = "admin"
	Gm     Role = "gm"
	Player Role = "player"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Gm:
		return true
	case Player:
		return true
	default:
		return false
	}
}

// Defines values for TurnStatus.
const (
	Locked     TurnStatus = "locked"
	Open       TurnStatus = "open"
	Processing TurnStatus = "processing"
	Published  TurnStatus = "published"
)

// Valid indicates whether the value is a known member of the TurnStatus enum.
func (e TurnStatus) Valid() bool {
	switch e {
	case Locked:
		return true
	case Open:
		return true
	case Processing:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Email    openapi_types.Email `json:"email"`
	Id       int64               `json:"id"`
	IsActive bool                `json:"isActive"`
	IsAdmin  bool                `json:"isAdmin"`
	Roles    []Role              `json:"roles"`
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken      string              `json:"accessToken"`
	ExpiresInSeconds int                 `json:"expiresInSeconds"`
	RefreshToken     string              `json:"refreshToken"`
	TokenType        AuthTokensTokenType `json:"tokenType"`
}

// AuthTokensTokenType defines model for AuthTokens.TokenType.
type AuthTokensTokenType string

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Email    openapi_types.Email `json:"email"`
	IsActive *bool               `json:"isActive,omitempty"`
	IsAdmin  *bool               `json:"isAdmin,omitempty"`

	// Secret Optional. If omitted, a random passphrase is generated. Minimum 8 characters.
	Secret *string `json:"secret,omitempty"`
}

// CreateAccountResponse defines model for CreateAccountResponse.
type CreateAccountResponse struct {
	Account Account `json:"account"`

	// GeneratedSecret The plaintext secret, present only when one was generated (secret
	// omitted from the request). Shown once; only its hash is stored.
	GeneratedSecret *string `json:"generatedSecret,omitempty"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// DatabaseVersion defines model for DatabaseVersion.
type DatabaseVersion struct {
	// SchemaVersion Number of schema migrations applied to the open database (SQLite user_version).
	SchemaVersion int32 `json:"schemaVersion"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	RequestId *string `json:"requestId,omitempty"`
}

// Game defines model for Game.
type Game struct {
	Description *string    `json:"description,omitempty"`
	Id          int64      `json:"id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Status      GameStatus `json:"status"`
}

// GameStatus defines model for GameStatus.
type GameStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ListGamesResponse defines model for ListGamesResponse.
type ListGamesResponse struct {
	Games []Game `json:"games"`
}

// ListTurnsResponse defines model for ListTurnsResponse.
type ListTurnsResponse struct {
	Turns []Turn `json:"turns"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	User User `json:"user"`
}

// OrderMessage defines model for OrderMessage.
type OrderMessage struct {
	Line     *int                 `json:"line,omitempty"`
	Message  string               `json:"message"`
	Severity OrderMessageSeverity `json:"severity"`
}

// OrderMessageSeverity defines model for OrderMessage.Severity.
type OrderMessageSeverity string

// OrderSubmission defines model for OrderSubmission.
type OrderSubmission struct {
	FactionId   int64                  `json:"factionId"`
	GameId      int64                  `json:"gameId"`
	Id          int64                  `json:"id"`
	Status      OrderSubmissionStatus  `json:"status"`
	SubmittedAt time.Time              `json:"submittedAt"`
	TurnId      int64                  `json:"turnId"`
	Validation  *OrderValidationResult `json:"validation,omitempty"`
}

// OrderSubmissionStatus defines model for OrderSubmission.Status.
type OrderSubmissionStatus string

// OrderValidationResult defines model for OrderValidationResult.
type OrderValidationResult struct {
	Messages []OrderMessage `json:"messages"`
	Ok       bool           `json:"ok"`
}

// OrdersRequest defines model for OrdersRequest.
type OrdersRequest struct {
	FactionId int64  `json:"factionId"`
	Orders    string `json:"orders"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Role defines model for Role.
type Role string

// Turn defines model for Turn.
type Turn struct {
	GameId      int64      `json:"gameId"`
	Id          int64      `json:"id"`
	Label       string     `json:"label"`
	OrdersDueAt *time.Time `json:"ordersDueAt,omitempty"`
	Status      TurnStatus `json:"status"`
}

// TurnStatus defines model for TurnStatus.
type TurnStatus string

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	IsActive *bool `json:"isActive,omitempty"`
	IsAdmin  *bool `json:"isAdmin,omitempty"`

	// Secret New secret, minimum 8 characters.
	Secret *string `json:"secret,omitempty"`
}

// User defines model for User.
type User struct {
	DisplayName *string `json:"displayName,omitempty"`
	Id          int64   `json:"id"`
	Roles       []Role  `json:"roles"`
	Username    string  `json:"username"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Application Server application version (semver, including build metadata when available).
	Application string          `json:"application"`
	Database    DatabaseVersion `json:"database"`
}

// AccountId defines model for AccountId.
type AccountId = int64

// GameId defines model for GameId.
type GameId = int64

// SubmissionId defines model for SubmissionId.
type SubmissionId = int64

// TurnId defines model for TurnId.
type TurnId = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	Status *GameStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = CreateGameRequest

// SubmitOrdersJSONRequestBody defines body for SubmitOrders for application/json ContentType.
type SubmitOrdersJSONRequestBody = OrdersRequest

// ValidateOrdersJSONRequestBody defines body for ValidateOrders for application/json ContentType.
type ValidateOrdersJSONRequestBody = OrdersRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an account
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Exchange credentials for JWT tokens
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the presented refresh token or session family
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Exchange a refresh token for a new access token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// List games visible to the current user
	// (GET /games)
	ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams)
	// Create a game
	// (POST /games)
	CreateGame(w http.ResponseWriter, r *http.Request)
	// Get a game by id
	// (GET /games/{gameId})
	GetGame(w http.ResponseWriter, r *http.Request, gameId GameId)
	// List turns for a game
	// (GET /games/{gameId}/turns)
	ListTurns(w http.ResponseWriter, r *http.Request, gameId GameId)
	// Get a turn by id
	// (GET /games/{gameId}/turns/{turnId})
	GetTurn(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId)
	// Get an order submission
	// (GET /games/{gameId}/turns/{turnId}/orders/{submissionId})
	GetOrderSubmission(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId, submissionId SubmissionId)
	// Submit an order set for processing
	// (POST /games/{gameId}/turns/{turnId}/orders:submit)
	SubmitOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId)
	// Validate an order set without submitting it
	// (POST /games/{gameId}/turns/{turnId}/orders:validate)
	ValidateOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId)
	// Health check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get the authenticated user context
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Application and database schema version
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGame(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGame(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTurns operation middleware
func (siw *ServerInterfaceWrapper) ListTurns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTurns(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTurn operation middleware
func (siw *ServerInterfaceWrapper) GetTurn(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTurn(w, r, gameId, turnId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrderSubmission operation middleware
func (siw *ServerInterfaceWrapper) GetOrderSubmission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	// ------------- Path parameter "submissionId" -------------
	var submissionId SubmissionId

	err = runtime.BindStyledParameterWithOptions("simple", "submissionId", r.PathValue("submissionId"), &submissionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "submissionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrderSubmission(w, r, gameId, turnId, submissionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitOrders operation middleware
func (siw *ServerInterfaceWrapper) SubmitOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitOrders(w, r, gameId, turnId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateOrders operation middleware
func (siw *ServerInterfaceWrapper) ValidateOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "turnId" -------------
	var turnId TurnId

	err = runtime.BindStyledParameterWithOptions("simple", "turnId", r.PathValue("turnId"), &turnId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "turnId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateOrders(w, r, gameId, turnId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreateAccount)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/accounts/{accountId}", wrapper.UpdateAccount)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games", wrapper.ListGames)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/games", wrapper.CreateGame)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}", wrapper.GetGame)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}/turns", wrapper.ListTurns)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}", wrapper.GetTurn)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}/orders/{submissionId}", wrapper.GetOrderSubmission)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}/orders:submit", wrapper.SubmitOrders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/games/{gameId}/turns/{turnId}/orders:validate", wrapper.ValidateOrders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse CreateAccountResponse

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateAccount403JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
	Body      *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse Account

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAccount400JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAccount401JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateAccount403JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAccount404JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthTokens

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse AuthTokens

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListGamesRequestObject struct {
	Params ListGamesParams
}

type ListGamesResponseObject interface {
	VisitListGamesResponse(w http.ResponseWriter) error
}

type ListGames200JSONResponse ListGamesResponse

func (response ListGames200JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGames401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListGames401JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGameRequestObject struct {
	Body *CreateGameJSONRequestBody
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse Game

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGame400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGame401JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGame403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateGame403JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGameRequestObject struct {
	GameId GameId `json:"gameId"`
}

type GetGameResponseObject interface {
	VisitGetGameResponse(w http.ResponseWriter) error
}

type GetGame200JSONResponse Game

func (response GetGame200JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGame401JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGame403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetGame403JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGame404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGame404JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurnsRequestObject struct {
	GameId GameId `json:"gameId"`
}

type ListTurnsResponseObject interface {
	VisitListTurnsResponse(w http.ResponseWriter) error
}

type ListTurns200JSONResponse ListTurnsResponse

func (response ListTurns200JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurns401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTurns401JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurns403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListTurns403JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListTurns404JSONResponse struct{ NotFoundJSONResponse }

func (response ListTurns404JSONResponse) VisitListTurnsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurnRequestObject struct {
	GameId GameId `json:"gameId"`
	TurnId TurnId `json:"turnId"`
}

type GetTurnResponseObject interface {
	VisitGetTurnResponse(w http.ResponseWriter) error
}

type GetTurn200JSONResponse Turn

func (response GetTurn200JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurn401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTurn401JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurn403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetTurn403JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurn404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTurn404JSONResponse) VisitGetTurnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmissionRequestObject struct {
	GameId       GameId       `json:"gameId"`
	TurnId       TurnId       `json:"turnId"`
	SubmissionId SubmissionId `json:"submissionId"`
}

type GetOrderSubmissionResponseObject interface {
	VisitGetOrderSubmissionResponse(w http.ResponseWriter) error
}

type GetOrderSubmission200JSONResponse OrderSubmission

func (response GetOrderSubmission200JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmission401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOrderSubmission401JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmission403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetOrderSubmission403JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderSubmission404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrderSubmission404JSONResponse) VisitGetOrderSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrdersRequestObject struct {
	GameId GameId `json:"gameId"`
	TurnId TurnId `json:"turnId"`
	Body   *SubmitOrdersJSONRequestBody
}

type SubmitOrdersResponseObject interface {
	VisitSubmitOrdersResponse(w http.ResponseWriter) error
}

type SubmitOrders201JSONResponse OrderSubmission

func (response SubmitOrders201JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response SubmitOrders400JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SubmitOrders401JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders403JSONResponse struct{ ForbiddenJSONResponse }

func (response SubmitOrders403JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders404JSONResponse struct{ NotFoundJSONResponse }

func (response SubmitOrders404JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitOrders409JSONResponse struct{ ConflictJSONResponse }

func (response SubmitOrders409JSONResponse) VisitSubmitOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrdersRequestObject struct {
	GameId GameId `json:"gameId"`
	TurnId TurnId `json:"turnId"`
	Body   *ValidateOrdersJSONRequestBody
}

type ValidateOrdersResponseObject interface {
	VisitValidateOrdersResponse(w http.ResponseWriter) error
}

type ValidateOrders200JSONResponse OrderValidationResult

func (response ValidateOrders200JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response ValidateOrders400JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ValidateOrders401JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders403JSONResponse struct{ ForbiddenJSONResponse }

func (response ValidateOrders403JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateOrders404JSONResponse struct{ NotFoundJSONResponse }

func (response ValidateOrders404JSONResponse) VisitValidateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create an account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)
	// Exchange credentials for JWT tokens
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the presented refresh token or session family
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Exchange a refresh token for a new access token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// List games visible to the current user
	// (GET /games)
	ListGames(ctx context.Context, request ListGamesRequestObject) (ListGamesResponseObject, error)
	// Create a game
	// (POST /games)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Get a game by id
	// (GET /games/{gameId})
	GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error)
	// List turns for a game
	// (GET /games/{gameId}/turns)
	ListTurns(ctx context.Context, request ListTurnsRequestObject) (ListTurnsResponseObject, error)
	// Get a turn by id
	// (GET /games/{gameId}/turns/{turnId})
	GetTurn(ctx context.Context, request GetTurnRequestObject) (GetTurnResponseObject, error)
	// Get an order submission
	// (GET /games/{gameId}/turns/{turnId}/orders/{submissionId})
	GetOrderSubmission(ctx context.Context, request GetOrderSubmissionRequestObject) (GetOrderSubmissionResponseObject, error)
	// Submit an order set for processing
	// (POST /games/{gameId}/turns/{turnId}/orders:submit)
	SubmitOrders(ctx context.Context, request SubmitOrdersRequestObject) (SubmitOrdersResponseObject, error)
	// Validate an order set without submitting it
	// (POST /games/{gameId}/turns/{turnId}/orders:validate)
	ValidateOrders(ctx context.Context, request ValidateOrdersRequestObject) (ValidateOrdersResponseObject, error)
	// Health check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get the authenticated user context
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Application and database schema version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request UpdateAccountRequestObject

	request.AccountId = accountId

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGames operation middleware
func (sh *strictHandler) ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams) {
	var request ListGamesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGames(ctx, request.(ListGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGamesResponseObject); ok {
		if err := validResponse.VisitListGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(w http.ResponseWriter, r *http.Request) {
	var request CreateGameRequestObject

	var body CreateGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGame operation middleware
func (sh *strictHandler) GetGame(w http.ResponseWriter, r *http.Request, gameId GameId) {
	var request GetGameRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGame(ctx, request.(GetGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameResponseObject); ok {
		if err := validResponse.VisitGetGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTurns operation middleware
func (sh *strictHandler) ListTurns(w http.ResponseWriter, r *http.Request, gameId GameId) {
	var request ListTurnsRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTurns(ctx, request.(ListTurnsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTurns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTurnsResponseObject); ok {
		if err := validResponse.VisitListTurnsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTurn operation middleware
func (sh *strictHandler) GetTurn(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId) {
	var request GetTurnRequestObject

	request.GameId = gameId
	request.TurnId = turnId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTurn(ctx, request.(GetTurnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTurn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTurnResponseObject); ok {
		if err := validResponse.VisitGetTurnResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrderSubmission operation middleware
func (sh *strictHandler) GetOrderSubmission(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId, submissionId SubmissionId) {
	var request GetOrderSubmissionRequestObject

	request.GameId = gameId
	request.TurnId = turnId
	request.SubmissionId = submissionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrderSubmission(ctx, request.(GetOrderSubmissionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrderSubmission")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderSubmissionResponseObject); ok {
		if err := validResponse.VisitGetOrderSubmissionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitOrders operation middleware
func (sh *strictHandler) SubmitOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId) {
	var request SubmitOrdersRequestObject

	request.GameId = gameId
	request.TurnId = turnId

	var body SubmitOrdersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitOrders(ctx, request.(SubmitOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitOrdersResponseObject); ok {
		if err := validResponse.VisitSubmitOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ValidateOrders operation middleware
func (sh *strictHandler) ValidateOrders(w http.ResponseWriter, r *http.Request, gameId GameId, turnId TurnId) {
	var request ValidateOrdersRequestObject

	request.GameId = gameId
	request.TurnId = turnId

	var body ValidateOrdersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ValidateOrders(ctx, request.(ValidateOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ValidateOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ValidateOrdersResponseObject); ok {
		if err := validResponse.VisitValidateOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Dtdc9u2ln/lDLczm+7Qkp1kto365Kau15066VpO+hD73oHIIxENCLAAKEf16L/fwQdJUCQlObF8m/uU",
	"WAAOzvcneB8lIi8ER65VNLmPCiJJjhql/es0SUTJ9UVq/qA8mkQF0VkUR5zkGE0iUq/HkcQ/SyoxjSZa",
	"lhhHKskwJ+bgXMic6GgSUa7/92UURznlNC/zaHISR3pVoFvCBcpovY6jc5Lj4JULt/iY903LWU6VooIP",
	"3qrCLY9593Uph2/VbvHx7lsbUKoQXKGV748kvcI/S1Ta/JUIrpHb/5KiYDQhmgo+/kMJbn5rLv1G4jya",
	"RP81bnRn7FbV+ExKIa/8Je7KFFUiaWGARZPogi8JoylIf/E6jl4LPmc0eUIkPNWQ+JsV3FGdQVJKiVyD",
	"UTJQmmg06P0s5IymKfKnw++01BlybaBjCqVCCVQBFxoIY+IOU9ACSJKgUqAzqkCiEqVMLL5vhP5ZlDx9",
	"Sna62+GOOCzn9v51HL3jpNSZkPQvfEJ8Lo2t8kUM+KkwdhODkEC94iUSU8NbwpQ1QQ818HfWEUpRoNTU",
	"GQrmhLKWvblfahtTWlK+MBTTtNcuN20xjqg6TTRdotnuV2dCMCTcr6Y55f2LUjCHF9WYq13suhLM6oWH",
	"Q6Qkq8j5gsqtfDBoxzVRNWoNHtWltzUcMfsDE2u/RluvxUfkqss5p6R2NaClYZeTkLrgU0wETx23P5G8",
	"YBhNXh0fb/dohoa5RJUNX6DNyrX99T5CbgB9iH5EIlEGxFT7N7gSYr9xVwi5h4w+Pr2WSDR6JQsc7766",
	"llP+K/KFzkJeBJoXKFSKc1IyHU3mhCmMtyvY7s0KE4na7Q0N7a39D2EjuJiDyKnWxtgISMJTkUNBlCoy",
	"SRQa97VAjtI4tBFcOpnC95BkRJLEJByjKG5INifvhEyjXRJyvNmD295b9CloZfPbjKhyDes4qumYDnDl",
	"OkMoGDFa+kmD410MhURlgovgbAV3GXIQ3HnMGiA8c5tvuOclzKXIQWdYhctvRzDNxJ05m+APDhbVCjKi",
	"MsNjpYXEdHTDoz1U2xI0zDqThw1qaYviHrNzKcz9Lp1VrFy4vFNrlIZ5//hAjv46Pnp16/89uv2fb3YS",
	"Y8H4S/sI+oloMiMK36NUHuM2OU7MwXJbom/KfIYSxBzcRsjpQtrQpcDGMReRjaBEgRxSfx88m/7/r1Sj",
	"DeH/XDrw346sw/A+7mXcChYvnodJ3HFv0tiivIV4H+3taNmhPBEptpxuVIYxu0dmOSpFFhuHqmTE+ESj",
	"iLkLwUHg7QPltdplwNtFbPFsLu+j9Nzr3MM0de+AXan0oylxHJkcs9wZwA1dU7ezN2yH2l/DHGLQtL6y",
	"CoapJHNtw1siS6oNanFEqgSgIKWyemAQY6jNb0QmGV1i2hNA4+j/kDCdDStcQ3OjPeJjH3eWjTk2W49H",
	"J6Pj3Q7BXdLA6GPHr1RpwxI1jKypBPbPtKwC7sq0HMghfExBuAUfUxLuj48BthMfB7IXH7GgfDAC1CE6",
	"tJ4gbu/w/MYj7hUkNtCtz8XNZQPIi3I4y9rMG3eh0IF/icNSMjjuks071ePN7cE+at7KFOVl43jb9zHK",
	"Kz5uSZUDv911RLhESfUq9AuUz0UUR3dEcucT0ESS3UlzDWu7t7YkNb2XLlVz44Oqpswe/nlR9432qb72",
	"3ag6/tI2g0x2Zt1kgoX7r0RDmf2vKguUCtMBD1kDONUtJFKi8UhTq9vdOqbuFO2BtA24pAp529TQSuF9",
	"vf0KlakEesNM3Xqr+1KNhOLG44bUDcq9c2NH+l519nd2LRPpOL3YxJieYnqDUBuI6qsH0VeDfmW70m43",
	"UGFBP9QhhkLwEPrwvgoc3qN5xRCP1tleDARrFeEFIyuURrFyY0m2Gu0zFxvFeiPz41s7IzNk7YRjWhhE",
	"4NXxSZ9ZOo7/VOIWW+YlY2RmgLn27WemgYYP29LA2j4dEVszwQBWIBFTu5jzIvlo/Vghhcnqnfcvyhmj",
	"Khvwae+KdI/exhf0vIZaEG/wri6x8y9qK3SY9M6H8Y16giqjuW+GqoG9de0xunjtPGq7gVolCdKn4Yae",
	"Lye3NE2a3m1XIlOUS5QQ7AGfhcMzhfkSZQyUJ6xMjV3NSspSyFETUzS7xghZEmotpl0qu9z/iLAiI322",
	"WFXdu1i52Q3otEYC6gKoXU45tSxNsjM1sB1zZra5eFoar1n99XOlDr/8fh35nrNVcNeIrCFnWheuo22z",
	"rw5vXwuujWIfzalUGq7Optdw+tsFzIUEwgE/FShpjlwTBufCDTLucAbKymR0w2/4dUaVPUMVUNuNty08",
	"tgKVE8aA8BSSrJT8aC4p8pStRnAtkWg3aZhThkAU6AxvuPUJCSQeK4uGc+tHd9IkARwSRg3zR+DV4qfr",
	"t8rekRGeMpSgdDlTQCTe8KYR5vte1X12OiNIQY8SkeICue9wUW314qxFtqHZX3b620VQA1bFo3HbBXJS",
	"0GgSvRgdj17YYkJnVnxj3xlzRY5QPT7HuinbfBuB65UZksAfjOEuo0nm+OvqaEswF/zIRjkoOUOlbnjl",
	"DmEM3vcZPoBCbRuqzq0ZOFU7sL+zGjLOXCTRZGiY2iYhUA4bHcvBvmF8w5UAaq9UdZvRaQThXGiYIUhM",
	"xBLrLqNxC6RKedpN16hu8Pwo0tWjjX962+jrthGbQLs57Xx+fHIoHLZM8twWSOwBOxN7eXw8BL7GdxyM",
	"Zu2Rk91HWrM2e+jF7kPNcNOeeLX7RD2tte6vzHMiV7XkAzMw9kkWyjjU08qibs2Z2sDG9/UDgvXm44MP",
	"/Wg0W8bN44T1rTXfJNtuqVNktkCD2QpoOoKzJcoVzCmy1NqYn2X8AKTu1VeLN1yhtnZg6Ju11oDhXEPJ",
	"k4zwBaYjONXAkCht+/sNhEo5R3AKvE5aIC+VNStSnWolLz0m1sq0DmRivdncXiZ2/Gg41BOXYaMqLZp/",
	"e6N6uftEPbNvG5WTw35GVepszMTC5c9V3Gqrjm3oPVhlfP7lm+m5zUqWhJXY7gLataMgw24yU7/k6r11",
	"M3TfpQKtBuRTq18z1O7RQIsZqDJJ0LZ5Pk+dgvwxmny4DSV/9sn5k/C5gk2vfvn92k1ZVKgLJtls64Eo",
	"9VZFMOuHcR7tzuu6++zoubOIDkdFqaFuqH0+R2seXuFSfEQ7lfMOHU1yZNsUflIlJCi0/UeYk5yy1Ram",
	"+pPDXL1qvw84BG/7ujh/K8OwKzWTn8JAyIZIbSlkI2w4k+yXaz3eWWCflVTzIVsetHIT+1rvzxLlKngk",
	"WHdA9+Jja6p3e0CBdcdcPXJ7TxWdMQTHkUcwPnOrgwZLD9tPyKtXdnbY0YjFcfp2HQ8UXVdOw12l5dI6",
	"CeeXIAXD0UAhcu47HQerQsI3Ek9cgrhhY1eStv79CsqN3urBakyPUtTGOr53bc71oNWeo67FfiCL2sr6",
	"FDWhTH0lGea5qWtcn8iWRf0G+aDCzL/fXt92hTau59eDDtcOwKMDu8P2lL0vjJkNNpQYj7Xwc/2vQJ7W",
	"7eoa+45BOfYeQKjjezcW3GqYdpRzQNm6Bw/94vwqDdPwtGOYXyrDeOdO/1nCHtIeuwHY+D78RGKrDmzO",
	"/Q+oDptX9WhGs/o16ofJgVKUoEJ2Vmry1g+Dn0BPdu9sfWSzv15N3GuCh3cHP0PX44GyzqKuPTcPk0y2",
	"HxU8cSL5MCv5ShrZDzKsL+t8O/0IjBH9ICycnneMcm8L8G958N9qA/69Dn6mFYQtxBlRNGn1EIM3M981",
	"r2Cid28uruHk+AQu374/gzc33P/wHKav3767hrMb/pBm4mfY2CNHop5nVt06vN4D0m/6T21uVzrVtpw7",
	"qjNRavDPyChfANVDBpTZt8Z/bUs33HPkQ2YZGw+e+9wnyiVN7EcwsuS8epwx1NpyACHJMPkYUD5dKY25",
	"p9w9+Bgi+vKg5W/w9LWH2Ndhe+cRGkkm0TFFGOl+E2mp+RRqxyV6/gRvxxfY201yRZL9tsbJxD+S+G/V",
	"+3SF8NRudky44dXvYt797GMEv9mHET8AFyHezqr9GLBntHeOunqTckDxbb7u6fNCnjjK3Tum6pXMkMae",
	"BgwzjKq/f/GfyyxrqrrK3Abbfj7z4daEJCcXF/I2hwYJYZDiEpkocqN1bm8UR6Vk/j3NZDxmZl8mlJ68",
	"evX9dzbOeUQ2IXrbM0Qob7XV26Sm0+uRN4F18LvdWmdsU5rROSarhGEDxFK4FURXzf3RS+w56Pp+RBMm",
	"Fh5/XRbNoXPf2b3vq43r91f2oP3yuT7oys3uQeuJoXlqHAdlSFwDsh1xD8n77h6i/UDX9nWp0s4m4Bmp",
	"x/ffBoyrBp/r2/W/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
